/* Generated By:JavaCC: Do not edit this line. rubyConstants.java */
public interface rubyConstants {

  int EOF = 0;
  int palias = 5;
  int pbreak = 6;
  int pcase = 7;
  int pclass = 8;
  int pdef = 9;
  int pdefined = 10;
  int pdo = 11;
  int pelse = 12;
  int pelsif = 13;
  int pend = 14;
  int pensure = 15;
  int pfalse = 16;
  int ptrue = 17;
  int pfor = 18;
  int pif = 19;
  int pin = 20;
  int pmodule = 21;
  int pnext = 22;
  int pnew = 23;
  int pcapitalize = 24;
  int pnil = 25;
  int pretry = 26;
  int preturn = 27;
  int pself = 28;
  int psuper = 29;
  int pthen = 30;
  int pundef = 31;
  int punless = 32;
  int puntil = 33;
  int pwhen = 34;
  int pwhile = 35;
  int pyield = 36;
  int pputs = 37;
  int pprint = 38;
  int pinicio = 39;
  int pchomp = 40;
  int pelseif = 41;
  int pleap = 42;
  int ploop = 43;
  int tiempo = 44;
  int ahora = 45;
  int dia = 46;
  int mes = 47;
  int anio = 48;
  int hora = 49;
  int minuto = 50;
  int segundo = 51;
  int zona = 52;
  int pstring = 53;
  int pinteger = 54;
  int pboolean = 55;
  int preal = 56;
  int prational = 57;
  int pchar = 58;
  int pvar = 59;
  int pconst = 60;
  int parray = 61;
  int peach = 62;
  int pitem = 63;
  int Suma = 64;
  int Resta = 65;
  int Multip = 66;
  int Division = 67;
  int Mod = 68;
  int asignacion = 69;
  int Not = 70;
  int And = 71;
  int Or = 72;
  int XOr = 73;
  int Igual = 74;
  int Desigualdad = 75;
  int MayQue = 76;
  int MenQue = 77;
  int MayIgual = 78;
  int MenIgual = 79;
  int Pertenencia = 80;
  int parenizq = 81;
  int parender = 82;
  int llaveizq = 83;
  int llaveder = 84;
  int corizq = 85;
  int corder = 86;
  int puncoma = 87;
  int dospuntos = 88;
  int coma = 89;
  int punto = 90;
  int subrango = 91;
  int apostrofo = 92;
  int puntero = 93;
  int pesos = 94;
  int comilla = 95;
  int letramayus = 96;
  int letraminus = 97;
  int letras = 98;
  int digito = 99;
  int caracter = 100;
  int cad = 101;
  int formato = 102;
  int formato_sub = 103;
  int entero = 104;
  int decim = 105;
  int ident = 106;
  int arreglo_uni = 107;
  int arreglo_bid = 108;
  int llamado = 109;
  int cad_noval = 110;
  int sharp_coment = 111;
  int variable_instancia = 112;
  int variable_local = 113;
  int variable_global = 114;
  int constante = 115;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "\"\\n\"",
    "<palias>",
    "<pbreak>",
    "<pcase>",
    "<pclass>",
    "<pdef>",
    "<pdefined>",
    "<pdo>",
    "<pelse>",
    "<pelsif>",
    "<pend>",
    "<pensure>",
    "<pfalse>",
    "<ptrue>",
    "<pfor>",
    "<pif>",
    "<pin>",
    "<pmodule>",
    "<pnext>",
    "<pnew>",
    "<pcapitalize>",
    "<pnil>",
    "<pretry>",
    "<preturn>",
    "<pself>",
    "<psuper>",
    "<pthen>",
    "<pundef>",
    "<punless>",
    "<puntil>",
    "<pwhen>",
    "<pwhile>",
    "<pyield>",
    "<pputs>",
    "<pprint>",
    "<pinicio>",
    "<pchomp>",
    "<pelseif>",
    "<pleap>",
    "<ploop>",
    "<tiempo>",
    "<ahora>",
    "<dia>",
    "<mes>",
    "<anio>",
    "<hora>",
    "<minuto>",
    "<segundo>",
    "<zona>",
    "<pstring>",
    "<pinteger>",
    "<pboolean>",
    "<preal>",
    "<prational>",
    "<pchar>",
    "<pvar>",
    "<pconst>",
    "<parray>",
    "<peach>",
    "<pitem>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "<Not>",
    "<And>",
    "<Or>",
    "<XOr>",
    "\"==\"",
    "\"<>\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<Pertenencia>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\".\"",
    "\"..\"",
    "\"\\\'\"",
    "\"@\"",
    "\"$\"",
    "\"\\\"\"",
    "<letramayus>",
    "<letraminus>",
    "<letras>",
    "<digito>",
    "<caracter>",
    "<cad>",
    "<formato>",
    "<formato_sub>",
    "<entero>",
    "<decim>",
    "<ident>",
    "<arreglo_uni>",
    "<arreglo_bid>",
    "<llamado>",
    "<cad_noval>",
    "\"#\"",
    "<variable_instancia>",
    "<variable_local>",
    "<variable_global>",
    "<constante>",
  };

}
